#!/bin/sh

BINARY="linux-watchdog"

start() {
        printf 'Starting %s: ' "$BINARY"
        /usr/bin/$BINARY
        status=$?
        if [ "$status" -eq 0 ]; then
                echo "OK"
        else
                echo "FAIL"
        fi
        return "$status"
}

case "$1" in
        start|stop|restart)
                "$1";;
        reload)
                # Restart, since there is no true "reload" feature (does not
                # reconfigure/restart on SIGHUP, just closes all open files).
                restart;;
        *)
                echo "Usage: $0 {start|stop|restart|reload}"
                exit 1
esac